
name: ingestion_pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "10 19 * * 1-5"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run Python
        env:
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python src/ingest.py


        
